apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gkhr9j6ie-python
  janus-idp.io/tekton: gkhr9j6ie-python
  backstage.io/kubernetes-id: gkhr9j6ie-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gkhr9j6ie-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
