apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gkhr9j6ie-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gkhr9j6ie-python 
  name: gkhr9j6ie-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gkhr9j6ie-python 
